# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Lucas Saldanha
tagline:             'There is no spoon. Innovative software development in action.'
description:         'A place where I share some thoughts on software development and agile methodologies.<br><a href="https://twitter.com/lucascrsaldanha" target="_blank">@lucascrsaldanha</a>'
url:                 http://www.lucascrsaldanha.com
baseurl:             'http://lucassaldanha.github.io'
paginate:            5

# About/contact
author:
  name:              Lucas Saldanha
  url:               https://twitter.com/lucascrsaldanha
  email:             lucascrsaldanha@gmail.com

# Custom vars
version:             1.0.0
